name: Crypto Analysis Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run analysis pipeline
        run: python run_analysis_pipeline.py
        env:
          CRYPTOCOMPARE_API_KEY: ${{ secrets.CRYPTOCOMPARE_API_KEY }}
          LINE_CHANNEL_TOKEN:   ${{ secrets.LINE_CHANNEL_TOKEN }}
          LINE_USER_ID:         ${{ secrets.LINE_USER_ID }}